# see
# https://github.com/sarnobat/github_workflow_action_tutorial.c/blob/main/.github/workflows/cmake-multi-platform.yml

name: Build

on:
  push:
    branches: [ master, actionBuild ] # Or your main branch name
  pull_request:
    branches: [ master, actionBuild ]

jobs:
  build:
    runs-on: ubuntu-latest # Or a specific OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies (if any)
        # Example: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc libncurses-dev libpcre3 libpcre3-dev

      - name: Build with Make
        run: |
          ./configure
          make -j$(nproc) # -j$(nproc) for parallel builds

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: src/ccze # Replace with actual path
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.binary }}
          tag_name:  ${{ steps.tag.outputs.tag }}
